excerpt_separator: ""
pygments: false
markdown: kramdown
url: http://DeepakGitH.github.io
title: Deepak Sharma
tagline: Difficult things in Data Science
description: I am a data science practitioner and here I will talk about things I have found difficult and challenging and worth more elaboration
paginate: 5
permalink: /blog/:year/:month/:day/:title
